env: "RAILS_ENV=test DISPLAY=:99.0"
rvm:
  - 2.0.0
  - 2.3.0
  - 2.2.4

before_script:
  - "sh -c 'cd test_app && bundle && bundle exec rake db:drop db:migrate'"
  - "sh -e /etc/init.d/xvfb start"

branches:
  only:
    - master
