source 'http://rubygems.org'

gem 'rails', '4.2.6'
gem 'haml-rails'

gem 'sqlite3'

gem 'interpret', path: '..'
gem 'mysql2', '~> 0.3.0'

gem 'jquery-rails'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end